name: Test
on: [push,pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.11]
        make_target: [test, testacc, vet, website-test]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with:
        go-version: "${{ matrix.go }}"
    - run: bash scripts/license.sh
      if: matrix.make_target == 'testacc'
    - run: bash scripts/start-gitlab.sh
      if: matrix.make_target == 'testacc'
    - run: |
        export MAKE_TARGET=${{ matrix.make_target }}
        export GOFLAGS=-mod=vendor
        export GO111MODULE=on
        make $MAKE_TARGET
